services:
    code:
        image: mcr.microsoft.com/devcontainers/javascript-node:20
        volumes:
            - ..:/workspace
        command: sleep infinity
        network_mode: service:redis

    redis:
        image: redis:7-alpine
        volumes:
            - redis-data:/data

volumes:
    redis-data:
